const fs = require('fs')

module.exports = {
  // If project only contains files generated by GH, it’s safe.
  // We also special case IJ-based products .idea because it integrates with CRA:
  // https://github.com/facebookincubator/create-react-app/pull/368#issuecomment-243446094
  isSafeToCreateProjectIn (root) {
    const validFiles = [
      '.DS_Store',
      'Thumbs.db',
      '.git',
      '.gitignore',
      '.idea',
      'README.md',
      'LICENSE',
      'web.iml',
      '.hg',
      '.hgignore',
      '.hgcheck',
      '.npmignore',
      'mkdocs.yml',
      'docs',
      '.travis.yml',
      '.gitlab-ci.yml',
      '.gitattributes',
    ];

    return (
      !fs.existsSync(root) ||
      fs.readdirSync(root).every(file => validFiles.includes(file))
    );
  }
}
